/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@ionic/core/components';

import { defineCustomElement as defineIonAccordion } from '@ionic/core/components/ion-accordion.js';
import { defineCustomElement as defineIonAccordionGroup } from '@ionic/core/components/ion-accordion-group.js';
import { defineCustomElement as defineIonAvatar } from '@ionic/core/components/ion-avatar.js';
import { defineCustomElement as defineIonBackdrop } from '@ionic/core/components/ion-backdrop.js';
import { defineCustomElement as defineIonBadge } from '@ionic/core/components/ion-badge.js';
import { defineCustomElement as defineIonBreadcrumbs } from '@ionic/core/components/ion-breadcrumbs.js';
import { defineCustomElement as defineIonButtons } from '@ionic/core/components/ion-buttons.js';
import { defineCustomElement as defineIonCardContent } from '@ionic/core/components/ion-card-content.js';
import { defineCustomElement as defineIonCardHeader } from '@ionic/core/components/ion-card-header.js';
import { defineCustomElement as defineIonCardSubtitle } from '@ionic/core/components/ion-card-subtitle.js';
import { defineCustomElement as defineIonCardTitle } from '@ionic/core/components/ion-card-title.js';
import { defineCustomElement as defineIonCheckbox } from '@ionic/core/components/ion-checkbox.js';
import { defineCustomElement as defineIonChip } from '@ionic/core/components/ion-chip.js';
import { defineCustomElement as defineIonCol } from '@ionic/core/components/ion-col.js';
import { defineCustomElement as defineIonContent } from '@ionic/core/components/ion-content.js';
import { defineCustomElement as defineIonDatetime } from '@ionic/core/components/ion-datetime.js';
import { defineCustomElement as defineIonDatetimeButton } from '@ionic/core/components/ion-datetime-button.js';
import { defineCustomElement as defineIonFab } from '@ionic/core/components/ion-fab.js';
import { defineCustomElement as defineIonFabList } from '@ionic/core/components/ion-fab-list.js';
import { defineCustomElement as defineIonFooter } from '@ionic/core/components/ion-footer.js';
import { defineCustomElement as defineIonGrid } from '@ionic/core/components/ion-grid.js';
import { defineCustomElement as defineIonHeader } from '@ionic/core/components/ion-header.js';
import { defineCustomElement as defineIonImg } from '@ionic/core/components/ion-img.js';
import { defineCustomElement as defineIonInfiniteScroll } from '@ionic/core/components/ion-infinite-scroll.js';
import { defineCustomElement as defineIonInfiniteScrollContent } from '@ionic/core/components/ion-infinite-scroll-content.js';
import { defineCustomElement as defineIonInput } from '@ionic/core/components/ion-input.js';
import { defineCustomElement as defineIonItemDivider } from '@ionic/core/components/ion-item-divider.js';
import { defineCustomElement as defineIonItemGroup } from '@ionic/core/components/ion-item-group.js';
import { defineCustomElement as defineIonItemOptions } from '@ionic/core/components/ion-item-options.js';
import { defineCustomElement as defineIonItemSliding } from '@ionic/core/components/ion-item-sliding.js';
import { defineCustomElement as defineIonLabel } from '@ionic/core/components/ion-label.js';
import { defineCustomElement as defineIonList } from '@ionic/core/components/ion-list.js';
import { defineCustomElement as defineIonListHeader } from '@ionic/core/components/ion-list-header.js';
import { defineCustomElement as defineIonMenu } from '@ionic/core/components/ion-menu.js';
import { defineCustomElement as defineIonMenuButton } from '@ionic/core/components/ion-menu-button.js';
import { defineCustomElement as defineIonMenuToggle } from '@ionic/core/components/ion-menu-toggle.js';
import { defineCustomElement as defineIonNav } from '@ionic/core/components/ion-nav.js';
import { defineCustomElement as defineIonNavLink } from '@ionic/core/components/ion-nav-link.js';
import { defineCustomElement as defineIonNote } from '@ionic/core/components/ion-note.js';
import { defineCustomElement as defineIonProgressBar } from '@ionic/core/components/ion-progress-bar.js';
import { defineCustomElement as defineIonRadio } from '@ionic/core/components/ion-radio.js';
import { defineCustomElement as defineIonRadioGroup } from '@ionic/core/components/ion-radio-group.js';
import { defineCustomElement as defineIonRange } from '@ionic/core/components/ion-range.js';
import { defineCustomElement as defineIonRefresher } from '@ionic/core/components/ion-refresher.js';
import { defineCustomElement as defineIonRefresherContent } from '@ionic/core/components/ion-refresher-content.js';
import { defineCustomElement as defineIonReorder } from '@ionic/core/components/ion-reorder.js';
import { defineCustomElement as defineIonReorderGroup } from '@ionic/core/components/ion-reorder-group.js';
import { defineCustomElement as defineIonRippleEffect } from '@ionic/core/components/ion-ripple-effect.js';
import { defineCustomElement as defineIonRow } from '@ionic/core/components/ion-row.js';
import { defineCustomElement as defineIonSearchbar } from '@ionic/core/components/ion-searchbar.js';
import { defineCustomElement as defineIonSegment } from '@ionic/core/components/ion-segment.js';
import { defineCustomElement as defineIonSegmentButton } from '@ionic/core/components/ion-segment-button.js';
import { defineCustomElement as defineIonSelect } from '@ionic/core/components/ion-select.js';
import { defineCustomElement as defineIonSelectOption } from '@ionic/core/components/ion-select-option.js';
import { defineCustomElement as defineIonSkeletonText } from '@ionic/core/components/ion-skeleton-text.js';
import { defineCustomElement as defineIonSpinner } from '@ionic/core/components/ion-spinner.js';
import { defineCustomElement as defineIonSplitPane } from '@ionic/core/components/ion-split-pane.js';
import { defineCustomElement as defineIonTab } from '@ionic/core/components/ion-tab.js';
import { defineCustomElement as defineIonText } from '@ionic/core/components/ion-text.js';
import { defineCustomElement as defineIonTextarea } from '@ionic/core/components/ion-textarea.js';
import { defineCustomElement as defineIonThumbnail } from '@ionic/core/components/ion-thumbnail.js';
import { defineCustomElement as defineIonTitle } from '@ionic/core/components/ion-title.js';
import { defineCustomElement as defineIonToggle } from '@ionic/core/components/ion-toggle.js';
import { defineCustomElement as defineIonToolbar } from '@ionic/core/components/ion-toolbar.js';
import { defineCustomElement as defineMedAccordionItem } from '@ionic/core/components/med-accordion-item.js';
import { defineCustomElement as defineMedAccordionList } from '@ionic/core/components/med-accordion-list.js';
import { defineCustomElement as defineMedAddCard } from '@ionic/core/components/med-add-card.js';
import { defineCustomElement as defineMedAgrupador } from '@ionic/core/components/med-agrupador.js';
import { defineCustomElement as defineMedAlertFixed } from '@ionic/core/components/med-alert-fixed.js';
import { defineCustomElement as defineMedAlternativas } from '@ionic/core/components/med-alternativas.js';
import { defineCustomElement as defineMedAlternativasA } from '@ionic/core/components/med-alternativas-a.js';
import { defineCustomElement as defineMedAlternativasB } from '@ionic/core/components/med-alternativas-b.js';
import { defineCustomElement as defineMedAutocomplete } from '@ionic/core/components/med-autocomplete.js';
import { defineCustomElement as defineMedBase } from '@ionic/core/components/med-base.js';
import { defineCustomElement as defineMedCalendar } from '@ionic/core/components/med-calendar.js';
import { defineCustomElement as defineMedCalendarDay } from '@ionic/core/components/med-calendar-day.js';
import { defineCustomElement as defineMedCaption } from '@ionic/core/components/med-caption.js';
import { defineCustomElement as defineMedCartaoRespostaItem } from '@ionic/core/components/med-cartao-resposta-item.js';
import { defineCustomElement as defineMedCartaoRespostaLista } from '@ionic/core/components/med-cartao-resposta-lista.js';
import { defineCustomElement as defineMedChartBar } from '@ionic/core/components/med-chart-bar.js';
import { defineCustomElement as defineMedChartBarHorizontal } from '@ionic/core/components/med-chart-bar-horizontal.js';
import { defineCustomElement as defineMedChartCategoria } from '@ionic/core/components/med-chart-categoria.js';
import { defineCustomElement as defineMedChartRadial } from '@ionic/core/components/med-chart-radial.js';
import { defineCustomElement as defineMedChartRadialContent } from '@ionic/core/components/med-chart-radial-content.js';
import { defineCustomElement as defineMedChartRadialLabel } from '@ionic/core/components/med-chart-radial-label.js';
import { defineCustomElement as defineMedCheckCard } from '@ionic/core/components/med-check-card.js';
import { defineCustomElement as defineMedContextMenu } from '@ionic/core/components/med-context-menu.js';
import { defineCustomElement as defineMedDownloadButton } from '@ionic/core/components/med-download-button.js';
import { defineCustomElement as defineMedDropdown } from '@ionic/core/components/med-dropdown.js';
import { defineCustomElement as defineMedEnunciado } from '@ionic/core/components/med-enunciado.js';
import { defineCustomElement as defineMedEnunciadoDiscursiva } from '@ionic/core/components/med-enunciado-discursiva.js';
import { defineCustomElement as defineMedFontZoom } from '@ionic/core/components/med-font-zoom.js';
import { defineCustomElement as defineMedHeader } from '@ionic/core/components/med-header.js';
import { defineCustomElement as defineMedImageZoom } from '@ionic/core/components/med-image-zoom.js';
import { defineCustomElement as defineMedItem } from '@ionic/core/components/med-item.js';
import { defineCustomElement as defineMedList } from '@ionic/core/components/med-list.js';
import { defineCustomElement as defineMedListItem } from '@ionic/core/components/med-list-item.js';
import { defineCustomElement as defineMedListItemAccordion } from '@ionic/core/components/med-list-item-accordion.js';
import { defineCustomElement as defineMedNavbar } from '@ionic/core/components/med-navbar.js';
import { defineCustomElement as defineMedOffline } from '@ionic/core/components/med-offline.js';
import { defineCustomElement as defineMedOption } from '@ionic/core/components/med-option.js';
import { defineCustomElement as defineMedPlusminus } from '@ionic/core/components/med-plusminus.js';
import { defineCustomElement as defineMedRateBar } from '@ionic/core/components/med-rate-bar.js';
import { defineCustomElement as defineMedRateLike } from '@ionic/core/components/med-rate-like.js';
import { defineCustomElement as defineMedTiles } from '@ionic/core/components/med-tiles.js';
import { defineCustomElement as defineMedToggle } from '@ionic/core/components/med-toggle.js';
import { defineCustomElement as defineMedToolbar } from '@ionic/core/components/med-toolbar.js';
import { defineCustomElement as defineMedTooltip } from '@ionic/core/components/med-tooltip.js';
import { defineCustomElement as defineMedType } from '@ionic/core/components/med-type.js';
import { defineCustomElement as defineMedVideoThumbnail } from '@ionic/core/components/med-video-thumbnail.js';
import { defineCustomElement as defineTpAccordion } from '@ionic/core/components/tp-accordion.js';
import { defineCustomElement as defineTpAccordionGroup } from '@ionic/core/components/tp-accordion-group.js';
import { defineCustomElement as defineTpChartBar } from '@ionic/core/components/tp-chart-bar.js';
import { defineCustomElement as defineTpInputContainer } from '@ionic/core/components/tp-input-container.js';
import { defineCustomElement as defineTpLoader } from '@ionic/core/components/tp-loader.js';

export const IonAccordion = /*@__PURE__*/createReactComponent<JSX.IonAccordion, HTMLIonAccordionElement>('ion-accordion', undefined, undefined, defineIonAccordion);
export const IonAccordionGroup = /*@__PURE__*/createReactComponent<JSX.IonAccordionGroup, HTMLIonAccordionGroupElement>('ion-accordion-group', undefined, undefined, defineIonAccordionGroup);
export const IonAvatar = /*@__PURE__*/createReactComponent<JSX.IonAvatar, HTMLIonAvatarElement>('ion-avatar', undefined, undefined, defineIonAvatar);
export const IonBackdrop = /*@__PURE__*/createReactComponent<JSX.IonBackdrop, HTMLIonBackdropElement>('ion-backdrop', undefined, undefined, defineIonBackdrop);
export const IonBadge = /*@__PURE__*/createReactComponent<JSX.IonBadge, HTMLIonBadgeElement>('ion-badge', undefined, undefined, defineIonBadge);
export const IonBreadcrumbs = /*@__PURE__*/createReactComponent<JSX.IonBreadcrumbs, HTMLIonBreadcrumbsElement>('ion-breadcrumbs', undefined, undefined, defineIonBreadcrumbs);
export const IonButtons = /*@__PURE__*/createReactComponent<JSX.IonButtons, HTMLIonButtonsElement>('ion-buttons', undefined, undefined, defineIonButtons);
export const IonCardContent = /*@__PURE__*/createReactComponent<JSX.IonCardContent, HTMLIonCardContentElement>('ion-card-content', undefined, undefined, defineIonCardContent);
export const IonCardHeader = /*@__PURE__*/createReactComponent<JSX.IonCardHeader, HTMLIonCardHeaderElement>('ion-card-header', undefined, undefined, defineIonCardHeader);
export const IonCardSubtitle = /*@__PURE__*/createReactComponent<JSX.IonCardSubtitle, HTMLIonCardSubtitleElement>('ion-card-subtitle', undefined, undefined, defineIonCardSubtitle);
export const IonCardTitle = /*@__PURE__*/createReactComponent<JSX.IonCardTitle, HTMLIonCardTitleElement>('ion-card-title', undefined, undefined, defineIonCardTitle);
export const IonCheckbox = /*@__PURE__*/createReactComponent<JSX.IonCheckbox, HTMLIonCheckboxElement>('ion-checkbox', undefined, undefined, defineIonCheckbox);
export const IonChip = /*@__PURE__*/createReactComponent<JSX.IonChip, HTMLIonChipElement>('ion-chip', undefined, undefined, defineIonChip);
export const IonCol = /*@__PURE__*/createReactComponent<JSX.IonCol, HTMLIonColElement>('ion-col', undefined, undefined, defineIonCol);
export const IonContent = /*@__PURE__*/createReactComponent<JSX.IonContent, HTMLIonContentElement>('ion-content', undefined, undefined, defineIonContent);
export const IonDatetime = /*@__PURE__*/createReactComponent<JSX.IonDatetime, HTMLIonDatetimeElement>('ion-datetime', undefined, undefined, defineIonDatetime);
export const IonDatetimeButton = /*@__PURE__*/createReactComponent<JSX.IonDatetimeButton, HTMLIonDatetimeButtonElement>('ion-datetime-button', undefined, undefined, defineIonDatetimeButton);
export const IonFab = /*@__PURE__*/createReactComponent<JSX.IonFab, HTMLIonFabElement>('ion-fab', undefined, undefined, defineIonFab);
export const IonFabList = /*@__PURE__*/createReactComponent<JSX.IonFabList, HTMLIonFabListElement>('ion-fab-list', undefined, undefined, defineIonFabList);
export const IonFooter = /*@__PURE__*/createReactComponent<JSX.IonFooter, HTMLIonFooterElement>('ion-footer', undefined, undefined, defineIonFooter);
export const IonGrid = /*@__PURE__*/createReactComponent<JSX.IonGrid, HTMLIonGridElement>('ion-grid', undefined, undefined, defineIonGrid);
export const IonHeader = /*@__PURE__*/createReactComponent<JSX.IonHeader, HTMLIonHeaderElement>('ion-header', undefined, undefined, defineIonHeader);
export const IonImg = /*@__PURE__*/createReactComponent<JSX.IonImg, HTMLIonImgElement>('ion-img', undefined, undefined, defineIonImg);
export const IonInfiniteScroll = /*@__PURE__*/createReactComponent<JSX.IonInfiniteScroll, HTMLIonInfiniteScrollElement>('ion-infinite-scroll', undefined, undefined, defineIonInfiniteScroll);
export const IonInfiniteScrollContent = /*@__PURE__*/createReactComponent<JSX.IonInfiniteScrollContent, HTMLIonInfiniteScrollContentElement>('ion-infinite-scroll-content', undefined, undefined, defineIonInfiniteScrollContent);
export const IonInput = /*@__PURE__*/createReactComponent<JSX.IonInput, HTMLIonInputElement>('ion-input', undefined, undefined, defineIonInput);
export const IonItemDivider = /*@__PURE__*/createReactComponent<JSX.IonItemDivider, HTMLIonItemDividerElement>('ion-item-divider', undefined, undefined, defineIonItemDivider);
export const IonItemGroup = /*@__PURE__*/createReactComponent<JSX.IonItemGroup, HTMLIonItemGroupElement>('ion-item-group', undefined, undefined, defineIonItemGroup);
export const IonItemOptions = /*@__PURE__*/createReactComponent<JSX.IonItemOptions, HTMLIonItemOptionsElement>('ion-item-options', undefined, undefined, defineIonItemOptions);
export const IonItemSliding = /*@__PURE__*/createReactComponent<JSX.IonItemSliding, HTMLIonItemSlidingElement>('ion-item-sliding', undefined, undefined, defineIonItemSliding);
export const IonLabel = /*@__PURE__*/createReactComponent<JSX.IonLabel, HTMLIonLabelElement>('ion-label', undefined, undefined, defineIonLabel);
export const IonList = /*@__PURE__*/createReactComponent<JSX.IonList, HTMLIonListElement>('ion-list', undefined, undefined, defineIonList);
export const IonListHeader = /*@__PURE__*/createReactComponent<JSX.IonListHeader, HTMLIonListHeaderElement>('ion-list-header', undefined, undefined, defineIonListHeader);
export const IonMenu = /*@__PURE__*/createReactComponent<JSX.IonMenu, HTMLIonMenuElement>('ion-menu', undefined, undefined, defineIonMenu);
export const IonMenuButton = /*@__PURE__*/createReactComponent<JSX.IonMenuButton, HTMLIonMenuButtonElement>('ion-menu-button', undefined, undefined, defineIonMenuButton);
export const IonMenuToggle = /*@__PURE__*/createReactComponent<JSX.IonMenuToggle, HTMLIonMenuToggleElement>('ion-menu-toggle', undefined, undefined, defineIonMenuToggle);
export const IonNav = /*@__PURE__*/createReactComponent<JSX.IonNav, HTMLIonNavElement>('ion-nav', undefined, undefined, defineIonNav);
export const IonNavLink = /*@__PURE__*/createReactComponent<JSX.IonNavLink, HTMLIonNavLinkElement>('ion-nav-link', undefined, undefined, defineIonNavLink);
export const IonNote = /*@__PURE__*/createReactComponent<JSX.IonNote, HTMLIonNoteElement>('ion-note', undefined, undefined, defineIonNote);
export const IonProgressBar = /*@__PURE__*/createReactComponent<JSX.IonProgressBar, HTMLIonProgressBarElement>('ion-progress-bar', undefined, undefined, defineIonProgressBar);
export const IonRadio = /*@__PURE__*/createReactComponent<JSX.IonRadio, HTMLIonRadioElement>('ion-radio', undefined, undefined, defineIonRadio);
export const IonRadioGroup = /*@__PURE__*/createReactComponent<JSX.IonRadioGroup, HTMLIonRadioGroupElement>('ion-radio-group', undefined, undefined, defineIonRadioGroup);
export const IonRange = /*@__PURE__*/createReactComponent<JSX.IonRange, HTMLIonRangeElement>('ion-range', undefined, undefined, defineIonRange);
export const IonRefresher = /*@__PURE__*/createReactComponent<JSX.IonRefresher, HTMLIonRefresherElement>('ion-refresher', undefined, undefined, defineIonRefresher);
export const IonRefresherContent = /*@__PURE__*/createReactComponent<JSX.IonRefresherContent, HTMLIonRefresherContentElement>('ion-refresher-content', undefined, undefined, defineIonRefresherContent);
export const IonReorder = /*@__PURE__*/createReactComponent<JSX.IonReorder, HTMLIonReorderElement>('ion-reorder', undefined, undefined, defineIonReorder);
export const IonReorderGroup = /*@__PURE__*/createReactComponent<JSX.IonReorderGroup, HTMLIonReorderGroupElement>('ion-reorder-group', undefined, undefined, defineIonReorderGroup);
export const IonRippleEffect = /*@__PURE__*/createReactComponent<JSX.IonRippleEffect, HTMLIonRippleEffectElement>('ion-ripple-effect', undefined, undefined, defineIonRippleEffect);
export const IonRow = /*@__PURE__*/createReactComponent<JSX.IonRow, HTMLIonRowElement>('ion-row', undefined, undefined, defineIonRow);
export const IonSearchbar = /*@__PURE__*/createReactComponent<JSX.IonSearchbar, HTMLIonSearchbarElement>('ion-searchbar', undefined, undefined, defineIonSearchbar);
export const IonSegment = /*@__PURE__*/createReactComponent<JSX.IonSegment, HTMLIonSegmentElement>('ion-segment', undefined, undefined, defineIonSegment);
export const IonSegmentButton = /*@__PURE__*/createReactComponent<JSX.IonSegmentButton, HTMLIonSegmentButtonElement>('ion-segment-button', undefined, undefined, defineIonSegmentButton);
export const IonSelect = /*@__PURE__*/createReactComponent<JSX.IonSelect, HTMLIonSelectElement>('ion-select', undefined, undefined, defineIonSelect);
export const IonSelectOption = /*@__PURE__*/createReactComponent<JSX.IonSelectOption, HTMLIonSelectOptionElement>('ion-select-option', undefined, undefined, defineIonSelectOption);
export const IonSkeletonText = /*@__PURE__*/createReactComponent<JSX.IonSkeletonText, HTMLIonSkeletonTextElement>('ion-skeleton-text', undefined, undefined, defineIonSkeletonText);
export const IonSpinner = /*@__PURE__*/createReactComponent<JSX.IonSpinner, HTMLIonSpinnerElement>('ion-spinner', undefined, undefined, defineIonSpinner);
export const IonSplitPane = /*@__PURE__*/createReactComponent<JSX.IonSplitPane, HTMLIonSplitPaneElement>('ion-split-pane', undefined, undefined, defineIonSplitPane);
export const IonTab = /*@__PURE__*/createReactComponent<JSX.IonTab, HTMLIonTabElement>('ion-tab', undefined, undefined, defineIonTab);
export const IonText = /*@__PURE__*/createReactComponent<JSX.IonText, HTMLIonTextElement>('ion-text', undefined, undefined, defineIonText);
export const IonTextarea = /*@__PURE__*/createReactComponent<JSX.IonTextarea, HTMLIonTextareaElement>('ion-textarea', undefined, undefined, defineIonTextarea);
export const IonThumbnail = /*@__PURE__*/createReactComponent<JSX.IonThumbnail, HTMLIonThumbnailElement>('ion-thumbnail', undefined, undefined, defineIonThumbnail);
export const IonTitle = /*@__PURE__*/createReactComponent<JSX.IonTitle, HTMLIonTitleElement>('ion-title', undefined, undefined, defineIonTitle);
export const IonToggle = /*@__PURE__*/createReactComponent<JSX.IonToggle, HTMLIonToggleElement>('ion-toggle', undefined, undefined, defineIonToggle);
export const IonToolbar = /*@__PURE__*/createReactComponent<JSX.IonToolbar, HTMLIonToolbarElement>('ion-toolbar', undefined, undefined, defineIonToolbar);
export const MedAccordionItem = /*@__PURE__*/createReactComponent<JSX.MedAccordionItem, HTMLMedAccordionItemElement>('med-accordion-item', undefined, undefined, defineMedAccordionItem);
export const MedAccordionList = /*@__PURE__*/createReactComponent<JSX.MedAccordionList, HTMLMedAccordionListElement>('med-accordion-list', undefined, undefined, defineMedAccordionList);
export const MedAddCard = /*@__PURE__*/createReactComponent<JSX.MedAddCard, HTMLMedAddCardElement>('med-add-card', undefined, undefined, defineMedAddCard);
export const MedAgrupador = /*@__PURE__*/createReactComponent<JSX.MedAgrupador, HTMLMedAgrupadorElement>('med-agrupador', undefined, undefined, defineMedAgrupador);
export const MedAlertFixed = /*@__PURE__*/createReactComponent<JSX.MedAlertFixed, HTMLMedAlertFixedElement>('med-alert-fixed', undefined, undefined, defineMedAlertFixed);
export const MedAlternativas = /*@__PURE__*/createReactComponent<JSX.MedAlternativas, HTMLMedAlternativasElement>('med-alternativas', undefined, undefined, defineMedAlternativas);
export const MedAlternativasA = /*@__PURE__*/createReactComponent<JSX.MedAlternativasA, HTMLMedAlternativasAElement>('med-alternativas-a', undefined, undefined, defineMedAlternativasA);
export const MedAlternativasB = /*@__PURE__*/createReactComponent<JSX.MedAlternativasB, HTMLMedAlternativasBElement>('med-alternativas-b', undefined, undefined, defineMedAlternativasB);
export const MedAutocomplete = /*@__PURE__*/createReactComponent<JSX.MedAutocomplete, HTMLMedAutocompleteElement>('med-autocomplete', undefined, undefined, defineMedAutocomplete);
export const MedBase = /*@__PURE__*/createReactComponent<JSX.MedBase, HTMLMedBaseElement>('med-base', undefined, undefined, defineMedBase);
export const MedCalendar = /*@__PURE__*/createReactComponent<JSX.MedCalendar, HTMLMedCalendarElement>('med-calendar', undefined, undefined, defineMedCalendar);
export const MedCalendarDay = /*@__PURE__*/createReactComponent<JSX.MedCalendarDay, HTMLMedCalendarDayElement>('med-calendar-day', undefined, undefined, defineMedCalendarDay);
export const MedCaption = /*@__PURE__*/createReactComponent<JSX.MedCaption, HTMLMedCaptionElement>('med-caption', undefined, undefined, defineMedCaption);
export const MedCartaoRespostaItem = /*@__PURE__*/createReactComponent<JSX.MedCartaoRespostaItem, HTMLMedCartaoRespostaItemElement>('med-cartao-resposta-item', undefined, undefined, defineMedCartaoRespostaItem);
export const MedCartaoRespostaLista = /*@__PURE__*/createReactComponent<JSX.MedCartaoRespostaLista, HTMLMedCartaoRespostaListaElement>('med-cartao-resposta-lista', undefined, undefined, defineMedCartaoRespostaLista);
export const MedChartBar = /*@__PURE__*/createReactComponent<JSX.MedChartBar, HTMLMedChartBarElement>('med-chart-bar', undefined, undefined, defineMedChartBar);
export const MedChartBarHorizontal = /*@__PURE__*/createReactComponent<JSX.MedChartBarHorizontal, HTMLMedChartBarHorizontalElement>('med-chart-bar-horizontal', undefined, undefined, defineMedChartBarHorizontal);
export const MedChartCategoria = /*@__PURE__*/createReactComponent<JSX.MedChartCategoria, HTMLMedChartCategoriaElement>('med-chart-categoria', undefined, undefined, defineMedChartCategoria);
export const MedChartRadial = /*@__PURE__*/createReactComponent<JSX.MedChartRadial, HTMLMedChartRadialElement>('med-chart-radial', undefined, undefined, defineMedChartRadial);
export const MedChartRadialContent = /*@__PURE__*/createReactComponent<JSX.MedChartRadialContent, HTMLMedChartRadialContentElement>('med-chart-radial-content', undefined, undefined, defineMedChartRadialContent);
export const MedChartRadialLabel = /*@__PURE__*/createReactComponent<JSX.MedChartRadialLabel, HTMLMedChartRadialLabelElement>('med-chart-radial-label', undefined, undefined, defineMedChartRadialLabel);
export const MedCheckCard = /*@__PURE__*/createReactComponent<JSX.MedCheckCard, HTMLMedCheckCardElement>('med-check-card', undefined, undefined, defineMedCheckCard);
export const MedContextMenu = /*@__PURE__*/createReactComponent<JSX.MedContextMenu, HTMLMedContextMenuElement>('med-context-menu', undefined, undefined, defineMedContextMenu);
export const MedDownloadButton = /*@__PURE__*/createReactComponent<JSX.MedDownloadButton, HTMLMedDownloadButtonElement>('med-download-button', undefined, undefined, defineMedDownloadButton);
export const MedDropdown = /*@__PURE__*/createReactComponent<JSX.MedDropdown, HTMLMedDropdownElement>('med-dropdown', undefined, undefined, defineMedDropdown);
export const MedEnunciado = /*@__PURE__*/createReactComponent<JSX.MedEnunciado, HTMLMedEnunciadoElement>('med-enunciado', undefined, undefined, defineMedEnunciado);
export const MedEnunciadoDiscursiva = /*@__PURE__*/createReactComponent<JSX.MedEnunciadoDiscursiva, HTMLMedEnunciadoDiscursivaElement>('med-enunciado-discursiva', undefined, undefined, defineMedEnunciadoDiscursiva);
export const MedFontZoom = /*@__PURE__*/createReactComponent<JSX.MedFontZoom, HTMLMedFontZoomElement>('med-font-zoom', undefined, undefined, defineMedFontZoom);
export const MedHeader = /*@__PURE__*/createReactComponent<JSX.MedHeader, HTMLMedHeaderElement>('med-header', undefined, undefined, defineMedHeader);
export const MedImageZoom = /*@__PURE__*/createReactComponent<JSX.MedImageZoom, HTMLMedImageZoomElement>('med-image-zoom', undefined, undefined, defineMedImageZoom);
export const MedItem = /*@__PURE__*/createReactComponent<JSX.MedItem, HTMLMedItemElement>('med-item', undefined, undefined, defineMedItem);
export const MedList = /*@__PURE__*/createReactComponent<JSX.MedList, HTMLMedListElement>('med-list', undefined, undefined, defineMedList);
export const MedListItem = /*@__PURE__*/createReactComponent<JSX.MedListItem, HTMLMedListItemElement>('med-list-item', undefined, undefined, defineMedListItem);
export const MedListItemAccordion = /*@__PURE__*/createReactComponent<JSX.MedListItemAccordion, HTMLMedListItemAccordionElement>('med-list-item-accordion', undefined, undefined, defineMedListItemAccordion);
export const MedNavbar = /*@__PURE__*/createReactComponent<JSX.MedNavbar, HTMLMedNavbarElement>('med-navbar', undefined, undefined, defineMedNavbar);
export const MedOffline = /*@__PURE__*/createReactComponent<JSX.MedOffline, HTMLMedOfflineElement>('med-offline', undefined, undefined, defineMedOffline);
export const MedOption = /*@__PURE__*/createReactComponent<JSX.MedOption, HTMLMedOptionElement>('med-option', undefined, undefined, defineMedOption);
export const MedPlusminus = /*@__PURE__*/createReactComponent<JSX.MedPlusminus, HTMLMedPlusminusElement>('med-plusminus', undefined, undefined, defineMedPlusminus);
export const MedRateBar = /*@__PURE__*/createReactComponent<JSX.MedRateBar, HTMLMedRateBarElement>('med-rate-bar', undefined, undefined, defineMedRateBar);
export const MedRateLike = /*@__PURE__*/createReactComponent<JSX.MedRateLike, HTMLMedRateLikeElement>('med-rate-like', undefined, undefined, defineMedRateLike);
export const MedTiles = /*@__PURE__*/createReactComponent<JSX.MedTiles, HTMLMedTilesElement>('med-tiles', undefined, undefined, defineMedTiles);
export const MedToggle = /*@__PURE__*/createReactComponent<JSX.MedToggle, HTMLMedToggleElement>('med-toggle', undefined, undefined, defineMedToggle);
export const MedToolbar = /*@__PURE__*/createReactComponent<JSX.MedToolbar, HTMLMedToolbarElement>('med-toolbar', undefined, undefined, defineMedToolbar);
export const MedTooltip = /*@__PURE__*/createReactComponent<JSX.MedTooltip, HTMLMedTooltipElement>('med-tooltip', undefined, undefined, defineMedTooltip);
export const MedType = /*@__PURE__*/createReactComponent<JSX.MedType, HTMLMedTypeElement>('med-type', undefined, undefined, defineMedType);
export const MedVideoThumbnail = /*@__PURE__*/createReactComponent<JSX.MedVideoThumbnail, HTMLMedVideoThumbnailElement>('med-video-thumbnail', undefined, undefined, defineMedVideoThumbnail);
export const TpAccordion = /*@__PURE__*/createReactComponent<JSX.TpAccordion, HTMLTpAccordionElement>('tp-accordion', undefined, undefined, defineTpAccordion);
export const TpAccordionGroup = /*@__PURE__*/createReactComponent<JSX.TpAccordionGroup, HTMLTpAccordionGroupElement>('tp-accordion-group', undefined, undefined, defineTpAccordionGroup);
export const TpChartBar = /*@__PURE__*/createReactComponent<JSX.TpChartBar, HTMLTpChartBarElement>('tp-chart-bar', undefined, undefined, defineTpChartBar);
export const TpInputContainer = /*@__PURE__*/createReactComponent<JSX.TpInputContainer, HTMLTpInputContainerElement>('tp-input-container', undefined, undefined, defineTpInputContainer);
export const TpLoader = /*@__PURE__*/createReactComponent<JSX.TpLoader, HTMLTpLoaderElement>('tp-loader', undefined, undefined, defineTpLoader);
